package by.itacademy.newsportal.controller;

public enum CommandName {
	
	REGISTRATION, 
	AUTHORIZATION, 
	UNKNOWN_COMMAND, 
	REGISTRAITION_NEW_USER,
	GET_USER,
	GO_TO_MAIN_PAGE,
	SET_LOCALE,
	GO_TO_SUCCESS_PAGE,
	GO_TO_NEWS_PAGE,
	GO_TO_PROFILE,
	LOG_OUT,
	UPDATE_USER,
	GO_TO_NEWS_REDACTOR,
	ADD_NEWS,
	UPDATE_NEWS,
	DELETE_NEWS,
	SEND_COMMENT,
	DELETE_COMMENT,
	PUT_NEWS_TO_FAVORITE,
	GO_TO_FAVORITE,
	DELETE_FROM_FAVORITE,
	GO_TO_USERS_NEWS,
	GO_TO_OFFERED_NEWS
}
